# Create a list with 20 elements of different data types
thinks = [1, 2, 3.5, "hello", True, 42, "world", None, 7.89, False, "python", 100, [1, 2, 3], {"key": "value"}, (4, 5), 0, -5, 3.14, "end", 99]

# Print all elements using indexing
print[thinks[0]]
print[thinks[1]]
print[thinks[2]]
print[thinks[3]]
print[thinks[4]]
print[thinks[5]]
print[thinks[6]]
print[thinks[7]]
print[thinks[8]]
print[thinks[9]]
print[thinks[10]]
print[thinks[11]]
print[thinks[12]]
print[thinks[13]]
print[thinks[14]]
print[thinks[15]]
print[thinks[16]]
print[thinks[17]]
print[thinks[18]]
print[thinks[19]]
