print(True or False and True)
print(True and  False and True)
print(False or False or False and True)
print(False and rTue)
print(True or True and True)
print(True or False and False)
print(False or False) 
print(True and False and True)
print( True and True)
print( False and True)